Es 5
nikiforov-org/elpts-system.ru pull request #7
Opened 2024-01-29 17:41 UTC by Vehsemel

I made a navbar for the site. Updated it.

2024-01-29 17:54 UTC, nikiforov-org commented on index.html
> +                        <a href="#">
Убери внешний тэг А, А не должен быть вложен в А. Поправь отступы.

2024-01-29 18:01 UTC, nikiforov-org requested changes

2024-01-29 18:01 UTC, nikiforov-org commented on index.html
> +                <div class="nav_top_block_end">
Зачем придумывать лишний класс .nav_top_block_end?
В CSS можно использовать .nav_top_block:last-child

2024-01-29 18:01 UTC, nikiforov-org commented on index.html
> +                    <a href="#22">
А вложен в А

2024-01-29 18:01 UTC, nikiforov-org commented on index.html
> +                        <a href="#">zakaz@elptssistem.ru</a>
<a href="mailto:zakaz@elptssistem.ru">zakaz@elptssistem.ru</a>
Тогда при клике будет открываться почтовая программа

2024-01-29 18:01 UTC, nikiforov-org commented on index.html
> +                    <a href="#">
А вложен в А

2024-01-29 18:01 UTC, nikiforov-org commented on index.html
> +                    <a class="link_nav_top_block_end" href="#" >
логичнее использовать название класса .nav_top_block_link. например
Ты читал про БЭМ?
Используй этот подход. Когда будем учить SCSS поймёшь почему

2024-01-30 04:34 UTC, nikiforov-org commented on css/style.css
> +  color: #ffffff;
Свойства
```
display: flex;
align-items: center;
```
наследуются от .nav_top_block, их писать не нужно

2024-01-30 04:40 UTC, nikiforov-org commented on index.html
> +                    <a href="#" class="nav_top_block">
Здесь у тебя класс `.nav_top_block` внутри `.nav_top_block`.
Так писать не надо, может, из-за этого у тебя проблема с `:last-child`?

2024-01-30 04:42 UTC, nikiforov-org commented on index.html
> +                        <div class="nav_top_block_border">
Ну вынеси ты этот блок правее, на одну линию с `<a>`, Сразу же в глаза бросается.

2024-01-30 04:43 UTC, nikiforov-org commented on index.html
> +                                <p>РЕГИСТРАЦИЯ В СЭП ЗДЕСЬ </p>
Зачем там пробел после `РЕГИСТРАЦИЯ В СЭП ЗДЕСЬ `?

2024-01-30 04:45 UTC, nikiforov-org commented on index.html
> +                        Пн.- Пт. с 10:00 до 18:00; <br />
Здесь тоже пробел убери перед <br />

2024-01-30 05:26 UTC, nikiforov-org commented on css/style.css
> +.logo_nav_end{
пробела нет `.logo_nav_end{`
везде между блоками у тебя разные отступы, где одна линия, где две, где вообще нет
приучайся писать аккуратно
из двух кандидатов с одинаковым кодом выберут того, у кого он опрятнее

2024-01-30 05:28 UTC, nikiforov-org requested changes
Нужно поправить

2024-01-30 11:41 UTC, Vehsemel commented on index.html
> +                    <a href="#">
Fixed it.

2024-01-30 12:00 UTC, Vehsemel commented on css/style.css
> +  color: #ffffff;
Fixed it.

2024-01-30 12:11 UTC, Vehsemel commented on index.html
> +                    <a href="#" class="nav_top_block">
Fixed it.

2024-01-30 12:28 UTC, Vehsemel commented on index.html
> +                    <a href="#" class="nav_top_block">
Fixed it.
Yes, you're right, that was it.

2024-01-30 12:29 UTC, Vehsemel commented on index.html
> +                                <p>РЕГИСТРАЦИЯ В СЭП ЗДЕСЬ </p>
Fixed it.

2024-01-30 12:30 UTC, Vehsemel commented on index.html
> +                        Пн.- Пт. с 10:00 до 18:00; <br />
Fixed it.

2024-01-30 12:32 UTC, Vehsemel commented on css/style.css
> +.logo_nav_end{
Fixed it.

2024-01-30 12:37 UTC, Vehsemel commented on index.html
> +                        <div class="nav_top_block_border">
I did it, but I'm not sure what's right.

2024-01-30 12:58 UTC, Vehsemel commented on index.html
> +                        <a href="#">zakaz@elptssistem.ru</a>
Fixed it.

2024-01-30 12:58 UTC, Vehsemel commented on index.html
> +                <div class="nav_top_block_end">
Fixed it.

2024-01-30 12:58 UTC, Vehsemel commented on index.html
> +                    <a class="link_nav_top_block_end" href="#" >
Ok.

2024-01-30 17:06 UTC, nikiforov-org commented on index.html
> +                </div>
вот теперь всё хорошо видно: лишний `</div>` :)

2024-01-30 17:11 UTC, nikiforov-org commented on index.html
> +                    </a>
а здесь нет закрывающего `</div>`

2024-01-30 17:12 UTC, merged